NPM_MODULES:      # Node modules to provide in webpack-sandboxed. Must be locally installed.
  - z-shop-ui
# NPM_EXTERNALS:    # Node modules to provide in webpack-sandboxed. Must be locally installed.
#   - z-shop-ui
