sudo: false
branches:
  only:
    - master
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  yarn: true
  directories:
    - node_modules
    - packages/tessellate-bundler/node_modules
    - packages/tessellate-editor/node_modules
    - packages/tessellate-fragment/node_modules
    - packages/tessellate-viewer/node_modules
before_install:
  - .travis/before_install.sh
install:
  - npm install
  - npm install istanbul-combine coveralls codeclimate-test-reporter
script:
  - npm test
  - npm run dist
after_success:
  - ./node_modules/.bin/istanbul-combine -d coverage -p summary -r lcov -r html packages/tessellate-*/coverage/coverage*.json
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
  - ./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info
  - .travis/after_success.sh
git:
  depth: 1
