APP_PORT: 3002
MORGAN_FORMAT: dev  # Format preset for request logs.
MORGAN_THRESHOLD: 0 # Do not log requests with a status code less than this value.
FRAGMENT_BUNDLES: fragment-bundles-eu-west-1.s3.amazonaws.com
