APP_PORT: 3001
MORGAN_FORMAT: dev  # Format preset for request logs.
MORGAN_THRESHOLD: 0 # Do not log requests with a status code less than this value.
PUBLISH_TARGET: file://bundles
NPM_MODULES:        # Node modules to provide in webpack-sandboxed. Must be locally installed.
  - mosaic-component-example
# NPM_EXTERNALS:      # Node modules to provide in webpack-sandboxed. Must be locally installed.
#   - mosaic-component-example
